<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black"/>
    <meta name="format-detection" content="telephone=no">
    <meta name="HandheldFriendly" content="true" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>LightHub</title>
    <script src="/scripts/jquery-1.11.3.min.js"></script>
    <link rel="stylesheet" href="/styles/common.css">
    <link rel="stylesheet" href="/theme/minimalism/css/style.css">
</head>
<body>
<header>
    <div class="container">
        <div class="inner clearfix">
            <a class="title" href="<?=\Akari\system\tpl\TemplateUtil::url('/')?>">LightHub</a>
        </div>
    </div>
</header>
<div class="container">#SCREEN#</div>
<footer>
    <div class="container">
        <div class="inner">
            <small>
                <ul>
                    <li>本站檔案歸原作者所有。如若喜歡作品，請購買正版支持。</li>
                    <li>本站檔案皆來自互聯網，僅供學習、參考之用。</li>
                    <li>本站分享檔案僅供學術參考，請於下載後廿四小時內刪除！</li>
                    <li>如有版權問題請 <a href="mailto:">電郵</a> 告知，將立即刪除！</li>
                </ul>
            </small>
        </div>
    </div>
</footer>
</body>
</html>