<html>
    <head>
        <meta charset="utf-8" />
        <title>Backstage</title>
        
        <style>
            .field {
                display: block;
                margin: 10px 0;
            }
            
            .field label {
                display: block;
            }
            
            .menu {
                display: block;
                list-style: none;
                margin: 0;
                padding: 0;
                margin: 10px 0;
                padding: 10px 15px;
                background: #eee;
            }
            
            .menu a {
                color: #333;
            }
            
            .menu li {
                display: block;
                float: left;
                padding: 0;
                margin: 0;
                margin-right: 10px;
            }
            
            table {
                border-collapse: collapse;
            }
            
            thead {
                background: #eee;
            }
            
            tbody tr:nth-of-type(even) {
                background: #eee;
            }
        </style>
    </head>

    <body>
        #SCREEN#
    </body>
</html>