<?php
$class = ( isset($detail->path) ) ? "has-download" : "";
?>
<section class="post <?=$class?>">
    <div class="inner">
        <div class="background"></div>
        <div class="stamp"></div>
        <div class="post-frame">
            <div class="post-header">
                <h3 class="post-title">
                    <a href="<?=\Akari\system\tpl\TemplateUtil::url('/post', ['id' => $id + 1])?>"><?=$detail->title?></a>
                </h3>
                <div class="post-info">
                    <small><?=strftime("%F %A",$detail->createAt)?></small>
                </div>
            </div>
            <article class="content"><?=$detail->content?></article>
            <?php if ( isset($detail->path) ) { ?>
                <a class="download" target="_blank" href="<?=$detail->path?>">Download .epub file</a>
            <?php } ?>
        </div>
    </div>
</section>